/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.danhmuc;

import controller.DanhMucChi;

/**
 *
 * @author phanh
 */
public class ChiJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ChiJPanel
     */
    public ChiJPanel() {
        initComponents();
        DanhMucChi.populateDanhmucComboBox(Danhmuc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Danhmuc = new javax.swing.JComboBox<>();
        ThemMuc = new javax.swing.JButton();
        Xoamuc = new javax.swing.JButton();
        Suamuc = new javax.swing.JButton();

        ThemMuc.setText("Thêm mục");
        ThemMuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemMucActionPerformed(evt);
            }
        });

        Xoamuc.setText("Xóa mục");
        Xoamuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoaMucActionPerformed(evt);
            }
        });

        Suamuc.setText("Sửa mục");
        Suamuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuaMucActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Danhmuc, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ThemMuc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Xoamuc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Suamuc)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Danhmuc, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ThemMuc)
                    .addComponent(Xoamuc)
                    .addComponent(Suamuc))
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
 
    private void ThemMucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemMucActionPerformed
        DanhMucChi.themMucActionPerformed(Danhmuc);
    }//GEN-LAST:event_ThemMucActionPerformed

    private void XoaMucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoaMucActionPerformed
        DanhMucChi.XoaMucActionPerformed(Danhmuc);
    }//GEN-LAST:event_XoaMucActionPerformed

    private void SuaMucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuaMucActionPerformed
        DanhMucChi.SuaMucActionPerformed(Danhmuc);
    }//GEN-LAST:event_SuaMucActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Danhmuc;
    private javax.swing.JButton Suamuc;
    private javax.swing.JButton ThemMuc;
    private javax.swing.JButton Xoamuc;
    // End of variables declaration//GEN-END:variables
}
