/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.danhmuc;
import controller.DanhMucThu;


/**
 *
 * @author phanh
 */
public class ThuJPanel extends javax.swing.JPanel {
     private final int ID_User;
    /**
     * Creates new form ThuJPanel
     */
    public ThuJPanel(int ID_User) {
        this.ID_User = ID_User;
        initComponents();
        DanhMucThu.populateDanhmucComboBox(Danhmuc,ID_User);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Danhmuc = new javax.swing.JComboBox<>();
        ThemMuc = new javax.swing.JButton();
        XoaMuc = new javax.swing.JButton();
        SuaMuc = new javax.swing.JButton();

        ThemMuc.setText("Thêm mục");
        ThemMuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemMucActionPerformed(evt);
            }
        });

        XoaMuc.setText("Xóa mục");
        XoaMuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoaMucActionPerformed(evt);
            }
        });

        SuaMuc.setText("Sửa mục");
        SuaMuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuaMucActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Danhmuc, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ThemMuc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(XoaMuc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SuaMuc)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(Danhmuc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(XoaMuc)
                    .addComponent(ThemMuc)
                    .addComponent(SuaMuc))
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ThemMucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemMucActionPerformed
       DanhMucThu.themMucActionPerformed(Danhmuc,ID_User);
    }//GEN-LAST:event_ThemMucActionPerformed

    private void XoaMucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoaMucActionPerformed
       DanhMucThu.XoaMucActionPerformed(Danhmuc);
    }//GEN-LAST:event_XoaMucActionPerformed
    
    private void SuaMucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuaMucActionPerformed
       DanhMucThu.SuaMucActionPerformed(Danhmuc,ID_User);
    }//GEN-LAST:event_SuaMucActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Danhmuc;
    private javax.swing.JButton SuaMuc;
    private javax.swing.JButton ThemMuc;
    private javax.swing.JButton XoaMuc;
    // End of variables declaration//GEN-END:variables
}
