/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.debt;

/**
 *
 * @author sidac
 */
public class debtView extends javax.swing.JFrame {

    /**
     * Creates new form debtView
     */
    public debtView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        totalDebt = new javax.swing.JLabel();
        debtWrapTable = new javax.swing.JScrollPane();
        debtTable = new javax.swing.JTable();
        addBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        itemToDebt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        totalDebt.setText("Tổng nợ");
        jPanel1.add(totalDebt);
        totalDebt.setBounds(354, 10, 70, 14);

        debtTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nội dung", "Phải trả", "Ngày trả kế", "Còn lại", "Hạn chót", "Chủ nợ", "Trả "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        debtWrapTable.setViewportView(debtTable);
        if (debtTable.getColumnModel().getColumnCount() > 0) {
            debtTable.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanel1.add(debtWrapTable);
        debtWrapTable.setBounds(10, 70, 510, 170);

        addBtn.setText("Thêm");
        jPanel1.add(addBtn);
        addBtn.setBounds(10, 20, 59, 23);

        jButton2.setText("jButton2");
        jPanel1.add(jButton2);
        jButton2.setBounds(110, 20, 73, 23);

        itemToDebt.setText("jLabel1");
        itemToDebt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemToDebtMouseClicked(evt);
            }
        });
        jPanel1.add(itemToDebt);
        itemToDebt.setBounds(230, 20, 40, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 540, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemToDebtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemToDebtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_itemToDebtMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(debtView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(debtView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(debtView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(debtView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new debtView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTable debtTable;
    private javax.swing.JScrollPane debtWrapTable;
    private javax.swing.JLabel itemToDebt;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel totalDebt;
    // End of variables declaration//GEN-END:variables
}
