/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.debt;

/**
 *
 * @author sidac
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addDebtPanel = new javax.swing.JPanel();
        debtDetailLabel = new javax.swing.JLabel();
        detailOfDebtLabel = new javax.swing.JLabel();
        totalDebtValueLabel = new javax.swing.JLabel();
        ownerLabel = new javax.swing.JLabel();
        addDebtBtn = new javax.swing.JButton();
        paymentDeadlineLabel = new javax.swing.JLabel();
        paymentTypeLabel = new javax.swing.JLabel();
        paymentTypeValue = new javax.swing.JComboBox<>();
        payDateLabel = new javax.swing.JLabel();
        anylize = new javax.swing.JLabel();
        detailDebtValue = new javax.swing.JTextField();
        totalDebtValue = new javax.swing.JTextField();
        ownerValue = new javax.swing.JTextField();
        payDateValue = new javax.swing.JTextField();
        paymentDeadlineValue = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        addDebtPanel.setBackground(new java.awt.Color(255, 255, 255));
        addDebtPanel.setLayout(null);

        debtDetailLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        debtDetailLabel.setText("Thông tin nợ");
        addDebtPanel.add(debtDetailLabel);
        debtDetailLabel.setBounds(110, 10, 80, 17);

        detailOfDebtLabel.setText("Chi tiết");
        addDebtPanel.add(detailOfDebtLabel);
        detailOfDebtLabel.setBounds(20, 40, 50, 14);

        totalDebtValueLabel.setText("Tổng nợ:");
        addDebtPanel.add(totalDebtValueLabel);
        totalDebtValueLabel.setBounds(20, 130, 50, 14);

        ownerLabel.setText("Chủ nợ:");
        addDebtPanel.add(ownerLabel);
        ownerLabel.setBounds(20, 170, 40, 14);

        addDebtBtn.setText("Thêm");
        addDebtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDebtBtnActionPerformed(evt);
            }
        });
        addDebtPanel.add(addDebtBtn);
        addDebtBtn.setBounds(120, 210, 59, 23);

        paymentDeadlineLabel.setText("Hạn cuối: ");
        addDebtPanel.add(paymentDeadlineLabel);
        paymentDeadlineLabel.setBounds(160, 40, 50, 14);

        paymentTypeLabel.setText("Trả theo: ");
        addDebtPanel.add(paymentTypeLabel);
        paymentTypeLabel.setBounds(160, 80, 50, 14);

        paymentTypeValue.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tháng", "Toàn bộ" }));
        addDebtPanel.add(paymentTypeValue);
        paymentTypeValue.setBounds(230, 80, 65, 20);

        payDateLabel.setText("Ngày trả: ");
        addDebtPanel.add(payDateLabel);
        payDateLabel.setBounds(160, 120, 49, 14);

        anylize.setText("(Dự đoán: cần x tháng)");
        addDebtPanel.add(anylize);
        anylize.setBounds(160, 160, 120, 14);

        detailDebtValue.setText("jTextField1");
        detailDebtValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailDebtValueActionPerformed(evt);
            }
        });
        addDebtPanel.add(detailDebtValue);
        detailDebtValue.setBounds(20, 60, 100, 40);

        totalDebtValue.setText("jTextField1");
        addDebtPanel.add(totalDebtValue);
        totalDebtValue.setBounds(80, 130, 60, 20);

        ownerValue.setText("jTextField2");
        addDebtPanel.add(ownerValue);
        ownerValue.setBounds(80, 170, 60, 20);

        payDateValue.setText("jTextField3");
        addDebtPanel.add(payDateValue);
        payDateValue.setBounds(230, 120, 60, 20);

        paymentDeadlineValue.setText("jTextField1");
        paymentDeadlineValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentDeadlineValueActionPerformed(evt);
            }
        });
        addDebtPanel.add(paymentDeadlineValue);
        paymentDeadlineValue.setBounds(230, 40, 60, 20);

        getContentPane().add(addDebtPanel);
        addDebtPanel.setBounds(50, 30, 310, 250);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addDebtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDebtBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addDebtBtnActionPerformed

    private void detailDebtValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailDebtValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detailDebtValueActionPerformed

    private void paymentDeadlineValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentDeadlineValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentDeadlineValueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDebtBtn;
    private javax.swing.JPanel addDebtPanel;
    private javax.swing.JLabel anylize;
    private javax.swing.JLabel debtDetailLabel;
    private javax.swing.JTextField detailDebtValue;
    private javax.swing.JLabel detailOfDebtLabel;
    private javax.swing.JLabel ownerLabel;
    private javax.swing.JTextField ownerValue;
    private javax.swing.JLabel payDateLabel;
    private javax.swing.JTextField payDateValue;
    private javax.swing.JLabel paymentDeadlineLabel;
    private javax.swing.JTextField paymentDeadlineValue;
    private javax.swing.JLabel paymentTypeLabel;
    private javax.swing.JComboBox<String> paymentTypeValue;
    private javax.swing.JTextField totalDebtValue;
    private javax.swing.JLabel totalDebtValueLabel;
    // End of variables declaration//GEN-END:variables
}
